const teamMembers = [
  {
    id: 1,
    name: "Ashraf Alshashaa",
    image: "https://ca.slack-edge.com/T0EJTUQ87-U03BGTV9SRH-ff4ba9bf6ebc-512",
    gitHubLink: " https://github.com/Ashraf-Alshashaa",
    TwitterLink: "",
    LinkedinLink: "https://www.linkedin.com/in/ashraf-alshashaa/",
    InstagramLink: " https://www.facebook.com/ashraf13795",
  },
  {
    id: 2,
    name: "İbrahim AKANÇAY",
    image: "https://ca.slack-edge.com/T0EJTUQ87-U03BGTL102E-cbde2ec79bd8-512",
    gitHubLink: "https://github.com/iakancay",
    TwitterLink: "",
    LinkedinLink: "https://www.linkedin.com/in/ibrahim-akancay-3817b1b2/",
    InstagramLink: "",
  },
  {
    id: 3,
    name: "Cynthia Amanat",
    image: "https://ca.slack-edge.com/T0EJTUQ87-U03BK87F7QU-8d695192f468-512",
    gitHubLink: "https://bit.ly/cynthiaAmant",
    TwitterLink: "",
    LinkedinLink: "https://bit.ly/393m36I",
    InstagramLink: "",
  },
  {
    id: 4,
    name: "Fadi-Naddaf",
    image: "https://ca.slack-edge.com/T0EJTUQ87-U02R2LCQYVD-dcbbebf13512-512",
    gitHubLink: "https://github.com/F-Naddaf",
    TwitterLink: "",
    LinkedinLink: "https://www.linkedin.com/in/fadi-naddaf-a04ba7196/",
    InstagramLink: "",
  },
  {
    id: 5,
    name: "Osama Bazbooz",
    image: "https://ca.slack-edge.com/T0EJTUQ87-U02DJTXAE81-2a18ce6d0c7a-512",
    gitHubLink: "",
    TwitterLink: "",
    LinkedinLink: "",
    InstagramLink: "",
  },
];
export default teamMembers;
